apiVersion: v1
kind: Secret
metadata:
  name: retail-app-secrets
  namespace: retail-app

type: Opaque

stringData:
  MYSQL_HOST: "<mysql-endpoint>"
  MYSQL_USER: "<mysql-user>"
  MYSQL_PASSWORD: "<mysql-password>"

  POSTGRES_HOST: "<postgres-endpoint>"
  POSTGRES_USER: "<postgres-user>"
  POSTGRES_PASSWORD: "<postgres-password>"

  DYNAMODB_TABLE: "bedrock-orders"