name: Deploy Retail Store

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: |
          echo "Current directory:"
          pwd

          echo ""
          echo "Repository root contents:"
          ls -la

          echo ""
          echo "Searching for retail-store-sample-app:"
          find . -type d | grep retail-store    

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
          --region us-east-1 \
          --name project-bedrock-cluster

      - name: Get Terraform Outputs
        working-directory: terraform

        run: |
          terraform init

          echo "MYSQL_ENDPOINT=$(terraform output -raw mysql_endpoint)" >> $GITHUB_ENV

          echo "POSTGRES_ENDPOINT=$(terraform output -raw postgres_endpoint)" >> $GITHUB_ENV

          echo "DYNAMODB_TABLE=$(terraform output -raw dynamodb_table_name)" >> $GITHUB_ENV

          echo "MYSQL_USERNAME=$(terraform output -raw mysql_username)" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=$(terraform output -raw mysql_password)" >> $GITHUB_ENV

          echo "POSTGRES_USERNAME=$(terraform output -raw postgres_username)" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=$(terraform output -raw postgres_password)" >> $GITHUB_ENV

      - name: Verify Terraform Outputs
        run: |
          echo "MYSQL_ENDPOINT=$MYSQL_ENDPOINT"
          echo "POSTGRES_ENDPOINT=$POSTGRES_ENDPOINT"
          echo "MYSQL_USERNAME=$MYSQL_USERNAME"
          echo "POSTGRES_USERNAME=$POSTGRES_USERNAME"

      - name: Verify Cluster
        run: |
          kubectl get nodes

      - name: Create Namespace
        run: |
          kubectl create namespace retail-app \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl get ns retail-app   

      - name: Initialize Catalog Database
        run: |
          kubectl delete pod mysql-init --ignore-not-found=true

          kubectl run mysql-init \
          
            --restart=Never \
            --image=mysql:8 \
            --env="MYSQL_PWD=${MYSQL_PASSWORD}" \
            --command -- \
            mysql \
            -h ${MYSQL_ENDPOINT} \
            -u ${MYSQL_USERNAME} \
            -e "CREATE DATABASE IF NOT EXISTS catalog;"


      - name: Initialize Orders Database
        run: |
          kubectl delete pod mysql-init --ignore-not-found=true

          kubectl run postgres-init \

            --restart=Never \
            --image=postgres:15 \
            --env="PGPASSWORD=${POSTGRES_PASSWORD}" \
            --command -- \
            bash -c '
            EXISTS=$(psql \
              -h '"${POSTGRES_ENDPOINT}"' \
              -U '"${POSTGRES_USERNAME}"' \
              -d postgres \
              -tAc "SELECT 1 FROM pg_database WHERE datname='\''orders'\''")

            if [ "$EXISTS" != "1" ]; then
              psql \
                -h '"${POSTGRES_ENDPOINT}"' \
                -U '"${POSTGRES_USERNAME}"' \
                -d postgres \
                -c "CREATE DATABASE orders;"
            else
              echo "orders database already exists"
            fi
            '

      - name: Verify Databases
        run: |
          kubectl run mysql-check \
            --rm -i --restart=Never \
            --image=mysql:8 \
            --env="MYSQL_PWD=${MYSQL_PASSWORD}" \
            --command -- \
            mysql \
            -h ${MYSQL_ENDPOINT} \
            -u ${MYSQL_USERNAME} \
            -e "SHOW DATABASES;"

          kubectl run postgres-check \
            --rm -i --restart=Never \
            --image=postgres:15 \
            --env="PGPASSWORD=${POSTGRES_PASSWORD}" \
            --command -- \
            psql \
            -h ${POSTGRES_ENDPOINT} \
            -U ${POSTGRES_USERNAME} \
            -d postgres \
            -c "\l"
     
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Check Helm Version
        run: |
          helm version

      - name: Check Helm Plugins Before Install
        run: |
          helm version
          helm plugin list

      - name: Install Helm Diff Plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff --version v3.9.12

      - name: Verify Helm Plugin
        run: |
          helm plugin list

      - name: Install Helmfile
        run: |
          HELMFILE_VERSION=v0.170.1

          curl -Lo helmfile.tar.gz \
          https://github.com/helmfile/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION#v}_linux_amd64.tar.gz

          tar -xzf helmfile.tar.gz

          chmod +x helmfile

          sudo mv helmfile /usr/local/bin/

          helmfile --version

      - name: Verify Retail Store Files
        run: |
          pwd
          echo "Checking Retail Store directory..."
          ls -la retail-store-sample-app
          ls -la retail-store-sample-app/src
          ls -la retail-store-sample-app/src/app

      - name: Verify Helmfile
        working-directory: retail-store-sample-app/src/app
        run: |
          helmfile --version
          test -f helmfile.yaml
          echo "helmfile.yaml found"

      - name: Deploy Retail Store
        working-directory: retail-store-sample-app/src/app
        env:
          MYSQL_ENDPOINT: ${{ env.MYSQL_ENDPOINT }}
          POSTGRES_ENDPOINT: ${{ env.POSTGRES_ENDPOINT }}
          DYNAMODB_TABLE: ${{ env.DYNAMODB_TABLE }}
          INGRESS: "true"
          MYSQL_USERNAME: ${{ env.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          POSTGRES_USERNAME: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          helmfile --log-level debug apply

      - name: Wait For Deployments
        run: |
          kubectl rollout status deployment/catalog -n retail-app --timeout=10m || true
          kubectl rollout status deployment/carts -n retail-app --timeout=10m || true
          kubectl rollout status deployment/orders -n retail-app --timeout=10m || true
          kubectl rollout status deployment/checkout -n retail-app --timeout=10m || true
          kubectl rollout status deployment/ui -n retail-app --timeout=10m || true

      - name: Show Pod Details
        run: |
          kubectl get pods -o wide
          kubectl get deployments
          kubectl get svc
          kubectl get ingress

      - name: Investigate Deployment State
        run: |
          echo "=== Namespaces ==="
          kubectl get ns

          echo "=== Deployments ==="
          kubectl get deployments -A

          echo "=== Pods ==="
          kubectl get pods -A

          echo "=== Services ==="
          kubectl get svc -A

          echo "=== Ingresses ==="
          kubectl get ingress -A

          echo "=== Events ==="
          kubectl get events -A --sort-by=.lastTimestamp | tail -50

      - name: Verify Ingress
        run: |
          kubectl get ingress ui -n retail-app
          kubectl describe ingress ui -n retail-app

      - name: Get ALB DNS
        run: |
          echo "Waiting for ALB provisioning..."

          for i in {1..30}; do

            kubectl get ingress

            ALB_DNS=$(kubectl get ingress ui -n retail-app \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)

            if [ -n "$ALB_DNS" ]; then
              echo ""
              echo "===================================="
              echo "Retail Store URL:"
              echo "http://${ALB_DNS}"
              echo "===================================="

              echo "## Retail Store Deployment Successful 🚀" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "**Application URL:** http://${ALB_DNS}" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "Deployment completed successfully." >> $GITHUB_STEP_SUMMARY

              exit 0
            fi

            echo "ALB not ready yet... retrying in 20 seconds"
            sleep 20
          done

          echo "ERROR: ALB hostname was not assigned"
          kubectl describe ingress ui
          exit 1
          
      - name: Smoke Test Application
        run: |
          ALB_DNS=$(kubectl get ingress ui -n retail-app \
            -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

          echo "Testing application..."

          curl -I http://${ALB_DNS}

          curl -s http://${ALB_DNS} | head -20